apiVersion: v1
name: harvester-cluster-template
description: Cluster template for Harvester RKE2
version: 0.0.1
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
